services:
  - type: web
    name: inmobiliaria-dc
    env: java
    plan: free
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/*.jar
    envVars:
      - key: JAVA_VERSION
        value: 17
    healthCheckPath: /

databases:
  - name: inmobiliaria-db
    plan: free
    databaseName: inmobiliaria_dc