# Exported from Render on 2025-11-28T09:31:44Z
version: "1"
services:
  - type: web
    name: nmobiliaria-dc-dannra77
    runtime: docker
    repo: https://github.com/dannra77/Inmobiliaria-DC
    plan: free
    envVars:
      - key: SPRING_JPA_SHOW_SQL
        sync: false
      - key: JAVA_OPTS
        sync: false
      - key: SPRING_PROFILES_ACTIVE
        sync: false
    region: oregon
    dockerContext: .
    dockerfilePath: ./Dockerfile
    autoDeployTrigger: commit
