services:
  - type: web
    name: inmobiliaria-dc-dannra777
    plan: free
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/*.jar
    healthCheckPath: /

databases:
  - name: inmobiliaria-db-dannra77
    plan: free
    databaseName: inmobiliaria_dc