server:
  port: ${PORT:8080}  # ðŸ”¥ CLAVE: Leer variable PORT de Render

spring:
  datasource:
    url: jdbc:postgresql://dpg-d4kes924d50c73df8p0g-a.oregon-postgres.render.com:5432/inmobiliaria_dc
    username: inmobiliaria_user
    password: p9Gl3NIYhwK4aRKP3Qbt2UECVFijxos3
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

logging:
  level:
    org.springframework: WARN